from __future__ import annotations

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
DATA_DIR = (BASE_DIR / "../data").resolve()
FONTS_DIR = (BASE_DIR / "../fonts").resolve()
RUNS_DIR = (BASE_DIR / "runs").resolve()

YOLO_IMAGE_EXTS = {".jpg", ".jpeg", ".png", ".bmp"}
YOLO_SYNTH_DIR = (DATA_DIR / "synthesized").resolve()
YOLO_DATASET_DIR = (DATA_DIR / "yolo26_dataset").resolve()
YOLO_MODEL_NAME = "yolo26n.pt"
YOLO_EPOCHS = 240
YOLO_BATCH_SIZE = 64
YOLO_IMG_SIZE = 720
YOLO_TRAIN_RATIO = 0.7
YOLO_VAL_RATIO = 0.15
YOLO_RANDOM_SEED = 42
YOLO_MIN_BOX_EDGE = 12
YOLO_MIN_BOX_AREA = 16 * 16
FONT_PATH = (FONTS_DIR / "NotoSansCJKtc-Regular.otf").resolve()
YOLO_SRC_DETECT_DIR = (RUNS_DIR / "detect").resolve()
YOLO_DATA_RUNS_DIR = (DATA_DIR / "runs").resolve()
YOLO_HARD_NEGATIVE_POOL_ENABLED = True
YOLO_HARD_NEGATIVE_POOL_DIR = (DATA_DIR / "hard_negative_pool").resolve()
YOLO_HARD_NEG_INCLUDE_UNLABELED_BACKGROUND = True
YOLO_HARD_NEG_UNLABELED_BACKGROUND_DIR = (DATA_DIR / "not_synthesized").resolve()
YOLO_HARD_NEG_CONF_THRESHOLD = 0.3
YOLO_HARD_NEG_MAX_IOU_WITH_GT = 0.05
YOLO_HARD_NEG_MIN_CROP_EDGE = 24
YOLO_HARD_NEG_MIN_CROP_AREA = 24 * 24
YOLO_HARD_NEG_PREDICT_BATCH_SIZE = 1
YOLO_HARD_NEG_FALLBACK_TO_CPU_ON_OOM = True

HARD_NEG_MINE_SPLIT = "train"
HARD_NEG_IMGSZ = YOLO_IMG_SIZE
HARD_NEG_CONF_THRESHOLD = YOLO_HARD_NEG_CONF_THRESHOLD
HARD_NEG_MAX_IOU_WITH_GT = YOLO_HARD_NEG_MAX_IOU_WITH_GT
HARD_NEG_MIN_CROP_EDGE = YOLO_HARD_NEG_MIN_CROP_EDGE
HARD_NEG_MIN_CROP_AREA = YOLO_HARD_NEG_MIN_CROP_AREA
HARD_NEG_PREDICT_BATCH_SIZE = YOLO_HARD_NEG_PREDICT_BATCH_SIZE
HARD_NEG_INCLUDE_UNLABELED_BACKGROUND = YOLO_HARD_NEG_INCLUDE_UNLABELED_BACKGROUND
HARD_NEG_FALLBACK_TO_CPU_ON_OOM = YOLO_HARD_NEG_FALLBACK_TO_CPU_ON_OOM

RECOGNITION_VIDEO_PATH = (DATA_DIR / "videos/sample-day-1.mp4").resolve()
RECOGNITION_MODEL_PATH = (YOLO_SRC_DETECT_DIR / "train/weights/best.pt").resolve()
RECOGNITION_OUTPUT_PATH = (DATA_DIR / "recognized/sample_recognized_tracked.mp4").resolve()
RECOGNITION_SAVE_VIDEO = True
RECOGNITION_MAX_FRAMES = None
RECOGNITION_CHUNK_SIZE = 32
RECOGNITION_WORKERS = 16
RECOGNITION_CONFIDENCE = 0.25
RECOGNITION_IOU = 0.5

CUTOUT_IMAGE_EXTS = {".jpg", ".jpeg", ".png", ".bmp", ".tif", ".tiff"}
CUTOUT_INPUT_DIR = (DATA_DIR / "signs").resolve()
CUTOUT_OUTPUT_DIR = (DATA_DIR / "signs_cutout").resolve()
CUTOUT_MODEL_ID = "ZhengPeng7/BiRefNet"
CUTOUT_INFER_SIZE = 1024
CUTOUT_MASK_THRESHOLD = 0.5
CUTOUT_ALPHA_SOFT = False
CUTOUT_BBOX_PAD = 2

SYNTH_IMAGE_EXTS = CUTOUT_IMAGE_EXTS
SYNTH_COMPOSITES_PER_BACKGROUND = 4
SYNTH_MIN_SIGNS_PER_IMAGE = 1
SYNTH_MAX_SIGNS_PER_IMAGE = 4
SYNTH_BACKGROUND_DIR = (DATA_DIR / "not_synthesized").resolve()
SYNTH_SIGNS_DIR = (DATA_DIR / "signs_cutout").resolve()
SYNTH_OUTPUT_DIR = (DATA_DIR / "synthesized").resolve()

PROCESS_ROAD = 0
PROCESS_SIDEWALK = 1
PROCESS_BUILDING = 2
PROCESS_WALL = 3
PROCESS_FENCE = 4
PROCESS_POLE = 5
PROCESS_TRAFFIC_LIGHT = 6
PROCESS_TRAFFIC_SIGN = 7
PROCESS_VEGETATION = 8
PROCESS_TERRAIN = 9
PROCESS_SKY = 10
PROCESS_DYNAMIC_CLASSES = {11, 12, 13, 14, 15, 16, 17, 18}
PROCESS_PLACEMENT_SUPPORT_CLASSES = {
    PROCESS_SIDEWALK,
    PROCESS_BUILDING,
    PROCESS_WALL,
    PROCESS_FENCE,
    PROCESS_POLE,
    PROCESS_TRAFFIC_LIGHT,
    PROCESS_TRAFFIC_SIGN,
    PROCESS_VEGETATION,
    PROCESS_TERRAIN,
}
PROCESS_ANCHOR_CLASSES = {PROCESS_POLE, PROCESS_TRAFFIC_LIGHT, PROCESS_TRAFFIC_SIGN}
PROCESS_INVALID_PLACEMENT_CLASSES = {PROCESS_ROAD, PROCESS_SKY, *PROCESS_DYNAMIC_CLASSES}
PROCESS_MIN_SCALE = 0.08
PROCESS_MAX_SCALE = 0.34
PROCESS_MIN_TARGET_SIDE = 14
PROCESS_MIN_BBOX_EDGE = 12
PROCESS_MIN_BBOX_AREA = 16 * 16
PROCESS_MAX_OBJECT_FRACTION = 0.22
PROCESS_HARD_MASK_THRESHOLD = 0.5
PROCESS_MOTION_BLUR_PROB = 0.16
PROCESS_MOTION_BLUR_KERNEL_SIZES = (3, 5)
PROCESS_MOTION_BLUR_MAX_ANGLE = 12.0

FRAME_EXTRACT_OUTPUT_DIR = (DATA_DIR / "not_synthesized").resolve()
FRAME_EXTRACT_VIDEO_DIR = (DATA_DIR / "videos").resolve()
FRAME_EXTRACT_INTERVAL_SECONDS = 0.3
FRAME_EXTRACT_VIDEO_SUFFIX = ".mp4"
